#/usr/bin/bash

echo "# The Unix Workbench" > README.md
echo "by Johns Hopkins University on [coursera.org](https://www.coursera.org/)  " >> README.md
echo "<br/>**Last edit in:** " >> README.md
date +"%d/%b/%Y" >> README.md
echo "<br/>**Total line:** " >> README.md
wc -l guessinggame.sh | egrep -o "[0-9]{1,}" >> README.md
echo "<br/>*[link to Git Pages](https://maxfeshchuk.github.io/MaxFeshchuk.unix/Unix/)*" >> README.md
