echo "# The Unix Workbench" > README.md
echo "by Johns Hopkins University on [coursera.org](https://www.coursera.org/)  " >> README.md
echo "</br>**Curent date:** " >> README.md
date >> README.md
echo "</br>**Total line:** " >> README.md
egrep -c '' guessinggame.sh >> README.md
echo "*</br>[link to Git Pages](https://maxfeshchuk.github.io/MaxFeshchuk.unix/Unix/)*" >> README.md
